trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - master

resources:
- repo: self

variables:
  name: 'devopsdemo-template-rust'
  tagname: 'latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: Login to Docker registry
        inputs:
          command: login
          containerRegistry: registry # a service connection that you must set up first
      - script: echo "##vso[task.setvariable variable=tagname]$(git describe --tags)"
        displayName: Get version tag
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      - task: Docker@2
        displayName: Build Docker image
        inputs:
          command: build
          repository: $(name)
          arguments: -t app:latest
          tags: |
            $(tagname)
      - bash: |
          cd api_tests
          docker-compose run tests
          docker-compose run --entrypoint /bin/cat app /app/test-results.xml > ../test-results.xml
        displayName: Run Tests
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'test-results.xml'
          testRunTitle: Unit tests
          failTaskOnFailedTests: true
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'api_tests/results/api-test-results.xml'
          testRunTitle: API tests
          failTaskOnFailedTests: true
      ## Do not publish docker image by default
      #- task: Docker@2
      #  displayName: Push to Docker registry
      #  inputs:
      #    command: push
      #    repository: $(name)
      #    tags: |
      #      $(tagname)
